---
- name : Install default Apache Web Server
  hosts : prod_servers
  become : yes

  tasks : 
  - name : Install Apache Web Server
    apt : name=apache2 state=latest

  - name : Start Apache and Enable it on the every boot
    service : name=apache2 state=started enabled=yes
